name: Setup Flutter
description: setup shared Flutter environment for common use.

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.13.4

    - run: flutter pub get
      shell: bash
