name: watermeter
description: Another personal data assistant for XDU.
publish_to: "none"
version: 0.3.0+8

environment:
  sdk: ">=3.0.0"

dependencies:
  # Network
  dio: ^5.0.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  alice: ^0.3.3
  # Stroage Cache
  shared_preferences: ^2.0.15
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.3
  path_provider: ^2.0.11
  file_picker: ^5.2.5
  json_annotation: ^4.8.0
  # Deal with html
  beautiful_soup_dart: ^0.3.0
  # Setting
  settings_ui: ^2.0.2
  # Homepage and others
  easy_refresh: ^3.3.0+1
  sn_progress_dialog: ^1.1.3
  fluttertoast: ^8.2.2
  extended_nested_scroll_view: ^6.1.2
  # Others
  url_launcher: ^6.1.6
  jiffy: ^6.1.0
  icalendar_parser: any
  auto_size_text: ^3.0.0
  async: ^2.10.0 # For AsyncMemoizer
  graphic: ^2.2.0
  restart_app: ^1.2.1
  pretty_dio_logger: ^1.3.1
  calendar_date_picker2: ^0.5.2
  flutter_widget_from_html_core: ^0.10.3
  cached_network_image: ^3.2.3
  qr_flutter: ^4.1.0
  data_table_2: ^2.5.1
  flutter_native_splash: ^2.3.1
  get:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl:
  webview_flutter: ^4.2.2
  package_info_plus: ^4.1.0
  flutter_markdown: ^0.6.17+1
  flutter_layout_grid: ^2.0.4
  styled_widget: ^0.4.1
  ming_cute_icons: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/Icon-App-iTunes.png"
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Icon-App-iTunes.png
    - assets/Empty-Cover.jpg
    - assets/Credit.jpg
    - assets/Ray.jpg
    - assets/icon.png
