name: build for iOS

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: cd build/ios/iphoneos
    - run: mkdir Payload
    - run: mv Runner.app Payload/
    
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Payload.zip Payload


    - uses: actions/upload-artifact@v3
      with:
        name: Traintime-PDA.ipa
        path: /Users/runner/work/watermeter/watermeter/build/ios/iphoneos/Payload.zip
        if-no-files-found: error


