name: Release for Linux (Debian package)

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install build-essential
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install ninja-build
          sudo apt install -y libgtk-3-dev

      - name: Install Flutter
        run: |
          git submodule update --init --recursive

      - name: Prepare Flutter Dependencies
        run: |
          .flutter/bin/flutter config --no-analytics
          .flutter/bin/flutter pub get

      - name: Build APP
        run: |
          .flutter/bin/flutter build linux --release
          .flutter/bin/dart pub global activate flutter_to_debian
          export PATH="$PATH":"$HOME/.pub-cache/bin":".flutter/bin/"
          flutter_to_debian

      - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: Traintime_PDA_Ubuntu
          path: ${{ github.workspace }}/build/linux/x64/release/debian/
