name: Release for Android

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          sudo update-java-alternatives -a 

      - name: Install Flutter
        run: |
          git submodule update --init --recursive

      - name: Prepare Flutter Dependencies
        run: |
          .flutter/bin/flutter config --no-analytics
          .flutter/bin/flutter pub get

      - name: Signing APK
        run: |
          echo keyPassword=\${{ secrets.SIGNING_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.SIGNING_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.SIGNING_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=key.jks >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/key.jks

      - name: Build APK
        run: .flutter/bin/flutter build apk --split-per-abi

      - name: Released
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: >
            build/app/outputs/bundle/release/app-release.aab,
            build/app/outputs/flutter-apk/app-release.apk,
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk,
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk,
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          token: ${{ secrets.RELEASE_TOKEN }}
